const STORAGE_DESTINATIONS = {
  NOTION: "notion",
  LOCAL_MARKDOWN: "localMarkdown"
};

const SUPPORTED_STORAGE_DESTINATIONS = Object.values(STORAGE_DESTINATIONS);

module.exports = {
  STORAGE_DESTINATIONS,
  SUPPORTED_STORAGE_DESTINATIONS
};
