const STATUS_PROPERTY_NAME = "Status";
const TO_PROCESS_STATUS = "To Process";
const TRANSCRIPT_HEADING = "Transcript";
const NOTION_VERSION = "2022-06-28";
const BODY_BLOCK_LIMIT = 100;
const RICH_TEXT_CHUNK_SIZE = 1800;
const CODE_SEGMENTS_PER_BLOCK = 12;

module.exports = {
  STATUS_PROPERTY_NAME,
  TO_PROCESS_STATUS,
  TRANSCRIPT_HEADING,
  NOTION_VERSION,
  BODY_BLOCK_LIMIT,
  RICH_TEXT_CHUNK_SIZE,
  CODE_SEGMENTS_PER_BLOCK
};
